baseURL = 'http://mythreyiramesh.github.io/hugo-test'
languageCode = 'en-us'
title = 'Test Hugo Site'
theme = "ananke"

SectionPagesMenu = "main"

[params]
  text_color = "cdecff"
  body_classes = "avenir bg-washed-green"
  background_color_class = "bg-navy"
